import DOMPurify from "isomorphic-dompurify";

export function sanitizeHtml(html: string) {
  return DOMPurify.sanitize(html, {
    USE_PROFILES: {
      html: true,
    },
    ADD_ATTR: [
      "class",
      "style",
      "data-line",
      "data-language",
      "data-math-format",
      "data-display-mode",
      "data-tex",
      "data-latex",
      "data-math",
      "data-formula",
      "data-expr",
      "aria-hidden",
      "xmlns",
      "display",
      "encoding",

      "href",
      "src",
      "srcset",
      "sizes",
      "width",
      "height",

      "target",
      "rel",
      "loading",
      "decoding",
      "alt",
      "title",
    ],
    ADD_TAGS: [
      "math",
      "semantics",
      "annotation",
      "mrow",
      "mi",
      "mn",
      "mo",
      "ms",
      "mtext",
      "mspace",
      "mfrac",
      "msqrt",
      "mroot",
      "msup",
      "msub",
      "msubsup",
      "mover",
      "munder",
      "munderover",
      "mtable",
      "mtr",
      "mtd",
      "mstyle",
      "mfenced",
      "menclose",
      "mmultiscripts",
      "mprescripts",
      "none",
      "maligngroup",
      "malignmark",
      "annotation-xml",
    ],
  });
}